### ISSUE TITLE
Passthrough does not provide the IMoniotringProducer when a passive entity is created

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#58] opened 2016-12-03 18:11 UTC
- This failed an Ehcache test: https://github.com/ehcache/ehcache3/issues/1677
- This blocked Ehcache PR: https://github.com/ehcache/ehcache3/pull/1676

As a workaround, I'll check the null return. But we said that `IMonitoringProducer` was a platform-provided service and that it was always there. So I expect it to be there ;-)

When doing passthrough testing, when creating passive entity, the IMonitoringProducer provided by platform does not exist and is null.

Ses Ehcache test: 

`ClusteredStateRepositoryReplicationTest.testClusteredStateRepositoryReplication`

The IMonitoringProducer is null.

![screen shot 2016-12-03 at 13 04 56](https://cloud.githubusercontent.com/assets/61346/20861265/73782800-b959-11e6-9269-8168f350ab09.png)

I'll put a workaround at the moment that will disable management if IMonitoringProducer is not found, but this need to be resolved ASAP because we will do some HA test with passive entities and we will need the `IMonitoringProducer` to be there in passthrough when creating passive entities.

**Comment by jd0-sag** [comment] 2016-12-05 17:48
Are you running on the latest release?  I have a test that does pretty well the same thing (in order to test node interaction and best-efforts data from the passive) and it works fine.  The service is looked up the same way, too.

**Comment by mathieucarbou** [comment] 2016-12-05 18:00
@jd0-sag : Ehcache is using __1.0.13.beta__.

**Comment by jd0-sag** [comment] 2016-12-05 18:21
So, this problem is happening when the entity is created during replication _and_ synchronization (after restarting the active) or just in one path?

Given that we have a test doing the same lookup, without issue, you will probably need to debug into passthrough to see if the `ServiceProvider` is present or why else it fails to be resolved.  If anything, I would suspect that there might be something like a class loader mismatch but that would surprise me since we would probably see that in our tests.

**Comment by mathieucarbou** [comment] 2016-12-05 19:11
I think your right with your 1st hypothesis. If you look at the test, when the failure happened, the test thread was stopped at:

```
    clusterControl.terminateActive();
    clusterControl.waitForActive();
```

You also have some test like that ? killing active and wait after ?

**Comment by jd0-sag** [comment] 2016-12-05 20:45
I didn't have that in my test but, after adding it, everything still works.

Additionally, that shouldn't involve creating a passive entity (terminating the active will cause the previous passive to be promoted to active) and the waiting for active doesn't do anything.

Further, I don't see the thread being stopped there, in your screenshot, since you are looking at the server thread.

**Comment by mathieucarbou** [comment] 2016-12-05 21:52
I don't know what to say ;-) 
This is an ehcache test that i am not familiar with, I just saw that in this case, IMonotoringProducer was null.
So except by telling that what I observed is wrong, I don't know what I could tell you expect try checkout ehcache code and run the test and you will see ;-)

You just have to add these lines in the creation of PassiveEhcacheEntity:

```
IMonitoringProducer monitoringProducer = services.getService(new BasicServiceConfiguration<>(IMonitoringProducer.class));
Objects.requireNonNull(monitoringProducer)
```

And you will see the test failing.

**Comment by jd0-sag** [comment] 2016-12-05 22:12
Since you already have the test and can verify it, can you check to see what is in the `ServiceProvider` collection being consulted?

For this test, they can successfully request the `IMonitoringProducer` in the active case?

**Comment by mathieucarbou** [comment] 2016-12-05 23:13
I don't know because I only request the 'IMonitoringProducer' from a passive entity. We do not need it from an active entity.

**Comment by jd0-sag** [comment] 2016-12-07 06:50
Take a look to verify if this is a classloader issue (you should be able to see the instance there, resolving to a different instance of the same class).  We suspect that, if you are in a different classloader when `IMonitoringProducer` is loaded, you are getting a mismatch.  Passthrough doesn't have explicit support for `CommonComponent`.

**Comment by mathieucarbou** [comment] 2016-12-07 20:19
Here is what I did. I added:

```
    IMonitoringProducer monitoringProducer = services.getService(new BasicServiceConfiguration<>(IMonitoringProducer.class));
    System.out.println(getClass().getSimpleName() + " monitoringProducer=" + monitoringProducer + " classloader=" + (monitoringProducer == null ? null : monitoringProducer.getClass().getClassLoader()));
    Objects.requireNonNull(monitoringProducer);
```

In `EhcachePassiveEntity` and `EhcacheActiveEntity`, as first lines in the ctor.

Than I run `ClusteredStateRepositoryReplicationTest `.

Here is the output:

```
EhcachePassiveEntity monitoringProducer=null classloader=null
EhcacheActiveEntity monitoringProducer=null classloader=null
```

Here is how passthrough is initialized:

```
    this.clusterControl = PassthroughTestHelpers.createActivePassive(STRIPENAME,
        new PassthroughTestHelpers.ServerInitializer() {
          @Override
          public void registerServicesForServer(PassthroughServer server) {
            server.registerServerEntityService(new EhcacheServerEntityService());
            server.registerClientEntityService(new EhcacheClientEntityService());
            server.registerServerEntityService(new VoltronReadWriteLockServerEntityService());
            server.registerClientEntityService(new VoltronReadWriteLockEntityClientService());
            server.registerExtendedConfiguration(new OffHeapResourcesProvider(getOffheapResourcesType("test", 32, MemoryUnit.MB)));

            UnitTestConnectionService.addServerToStripe(STRIPENAME, server);
          }
        }
    );

    clusterControl.waitForActive();
    clusterControl.waitForRunningPassivesInStandby();
```

So... `IMonitoringProducer` is simply not there at all!

I tried to do the same thing in our test in tc-platform, and I am unable to reproduce. __BUT: we do not have passives and passive entities yet!__ So perhaps because of that. Or... perhaps because Ehcache is using its own `ConnectionService`: `UnitTestConnectionService`

Please have a look at `ClusteredStateRepositoryReplicationTest` in Ehcache. This test can be run directly from within the IDE and is fast.

So for the moment, we can leave this open. Once I'll add some HA testing, I'll check if I have the same issue. 
If yes, it means there's an issue in passthrough with passives and __it will be a blocker for us__. 
If not, then it means these failures are only in Ehcache, and it could be the way Ehcache does their testing with passthrough. Perhaps it has an impact on the `IMonitoringProducer`. __This will also be a blocker for us.__

**Comment by jd0-sag** [comment] 2016-12-07 22:28
`IMonitoringProducer` will never appear as a registered service provider since it is provided by the implementation.  In the case of passthrough, this is `PassthroughMonitoringProducer`.

The test that you did doesn't provide any information since the problem is with the classloader of `IMonitoringProducer` being different between the your requesting code and the code which actually implements it.  Since the `services.getService` is essentially looking something up by class instance match, this will fail if they are in different class loaders.

To determine if this is the case, you will need to take that example you had in the debugger and see why it failed to find the service.  Is there anything implementing `IMonitoringProducer` in the service registry being consulted, and just has a different class instance, or is it missing, altogether.

**Comment by jd0-sag** [comment] 2016-12-07 23:26
I looked into this (debugged why we weren't returning something in that test) and the problem is that there is no `IStripeMonitoring` implementation registered.  Since this means that the data can't be sent anywhere, it doesn't return a service.

Passthrough treats this the same way, on both the active and the passive, and then allows the wrapper to switch modes if the server becomes active.

The real server uses the same logic.

**Comment by jd0-sag** [comment] 2016-12-07 23:33
In our internal tests, we register an `IStripeMonitoring` service provider as a built-in but any mechanism to install this would work.

So, to summarize:  Both passthrough and core will return null for `IMonitoringProducer`, on both active and passive, is there is no `IStripeMonitoring` implementation registered.

The rationale being that this is the only way to receive data from the service and returning non-null would imply, to the caller, that the data was going somewhere.

**Comment by mathieucarbou** [comment] 2016-12-08 14:10
There's an issue with that @jd0-sag. On passive servers, an entity could just fetch a `IMonitoringProducer` and use it, whether there is a monitoring service or not, because the `IMonitoringProducer ` is just a "network bridge" in this case, and the monitoring service does nothing on passives. It is not related at all to any `IStripeMonitoring`. `IStripeMonitoring ` is just on actives ?

**Comment by jd0-sag** [comment] 2016-12-08 14:28
While the `IStripeMonitoring` is only consulted on the active, the stripe is consistently configured so we wouldn't expect only some servers in the stripe to have it.

**Comment by mathieucarbou** [comment] 2016-12-08 14:31
ok! so in this case, I'll change our implementation to support null `IMonitoringProducer` in our configuration object

**Closed** 2016-12-08 14:32 UTC
Labels: bug
