### ISSUE TITLE
PassthroughServerProcess.shutdown() does not call clear() on the ServiceProviders

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/tc-passthrough-testing#27] opened 2016-09-19 09:15 UTC
I assume that the clear() method on a ServiceProvider allows it to release any resources, but the passthrough code doesn't call it. I suspect that PassthroughServerProcess.shutdown() should loop over serviceProviders calling clear() on each.

**Comment by jd0-sag** [comment] 2016-09-19 13:14
While this method is not typically called in the normal server (and we rely on the "crash only" model), we should call this in the passthrough case since the process goes on and we don't want to leak resources, etc, when the server is explicitly shut down.

**Comment by jd0-sag** [comment] 2016-09-19 22:33
I talked with @myronkscott about this, a little further, and we realized that this isn't really appropriate, either.  In fact, we are still trying to think up the right way to handle this since the API is designed around the idea that you can't rely on any shutdown routine being called.

`clear()` is not analogous to a shutdown routine since it is called only in the case of a zap.  This is a signal to destroy any of the persistent resources associated with the service so that the state will be clean when it restarts so that it can re-sync the correct state from the active.

In the case of something like a restartable server, clearing the persistent storage when it went down would actually destroy the data it needs for restart.

This will take some thinking since the capability you actually need, in this case, is not provided, largely by design.  Correspondingly, if we were to add something to the API to support this, it would ONLY ever be called when running in passthrough.

**Comment by ChrisGreenaway** [comment] 2016-09-20 07:07
"clearing the persistent storage when it went down would actually destroy the data it needs for restart" - actually, all I need to do is release an open file handle. The data will stay on the disk ready for the restart.

It's not clear to me what you mean when you talk about zapping a server.

**Comment by jd0-sag** [comment] 2016-09-20 13:32
> all I need to do is release an open file handle

This is the crux of why we need to solve this is a different way.  It is more "close-like" than a `clear()`.

When a server which already has state joins a stripe, if the state is inconsistent with the rest of the stripe, the stripe will "zap" the server.  This means that it tells it to clear its state and restart as a fresh server to re-synchronize with the stripe.

**Comment by ChrisGreenaway** [comment] 2016-09-20 14:38
Yeah, it sounds like we need a close() style operation then.

That clear and resync from scratch sounds really expensive if someone has a stripe with a lot of storage.

**Comment by jd0-sag** [comment] 2016-09-20 14:49
The problem is that this kind of call will never happen, outside of passthrough, so we are hesitant to make it a first-class part of the API.

The approaches we have thought up would work, and don't pollute the core API, but are rather ugly:

* We could document that passthrough will check if any `ServiceProvider` implements `Closeable` and will call it on shutdown.  This is at least direct about the "test-only" nature of the behavior but is odd in that it is somewhat hidden
* Leave this up to the test being run to hold onto the instance and close it, itself.  This would require that the user's implementation likely do some hackish things to expose these internals to the test (which would be their own "test-only" code) and then they would have to infer server instance life-cycle, very directly, to know when to call that.

Let me know what you think about the `Closeable` idea, since it seems like the least of several evils.

Clear and re-sync is expensive but, what's more important in this case, is that it isn't what we want to do.  It actually means something different.

**Comment by jd0-sag** [comment] 2016-09-22 14:30
Talked to @myronkscott and we are in agreement that we could type-check on `Closeable` during server shutdown.

The unfortunate part of this is that it means `ServiceProvider` implementations which have closeable state will implement this interface which is called _only_ in the case of passthrough.  The real server will _never_ call this method.

Still, the only other alternative seemed to be to push the complexity up into the test which would specialize it against a test running on the multi-process server, which is the exact opposite of the goal of passthrough so this seemed like a better solution.

Hopefully, I can get an implementation of this released tonight or tomorrow morning.

**Comment by jd0-sag** [comment] 2016-09-22 16:29
Looking through this, it is going to be more complex than I originally though.  If we want to more faithfully life-cycle these ServiceProviders, we will also need to instantiate them at the right time.  Currently, they are instantiated for each server, when the test starts.  The same instance is then used by that server, no matter how many times it is "restarted".

If we want this to truly be a representative test environment, those should be instantiated each time a new server instance "comes online" and then we can call this `close()` when it "goes down".

This hopefully won't require too-substantial a re-work but it is definitely bigger than I had first hoped.

**Comment by jd0-sag** [comment] 2016-09-22 20:47
Now that I have a prototype, I didn't need to make as complex a set of changes as I originally suspected.  It turns out that we _do_ create a new `ServiceProvider` instance, each time a server is "started", and it only looked like we didn't (despite being given an instance of the provider, in test initialization, we actually only use it to determine the type of instances to create, later on).

**Closed** 2016-09-22 22:00 UTC
Labels: bug
